# LIST REPOSITORIES FOR A USER https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-repositories-for-a-user

# Can be one of: all, owner, member
TYPE: "owner"

# Can be one of: created, updated, pushed, full_name
SORT: "full_name"

# Can be one of: asc, desc
DIRECTION: "asc"

# (max 100)
PER_PAGE: 30

# Start collecting repo page 1
PAGE: 1

# CleanOutput
Private: "NO"
HTMLURL: "YES"
Description: "NO"
Fork: "NO"
CreatedAt: "NO"
UpdatedAt: "NO"
PushedAt: "NO"
GitURL: "NO"
SSHURL: "NO"
CloneURL: "YES"
SVNURL: "NO"
Size: "NO"
Language: "NO"